version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT}

      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
